name: "Thermowatt Smart Boiler"
description: "Cloud-to-Local bridge for Thermowatt / Ariston water heaters."
version: "1.7.2"
slug: "thermowatt_boiler"
arch:
  - aarch64
  - amd64
  - armv7
init: false
options:
  email: ""
  password: ""
  element_wattage: 3000
schema:
  email: str
  password: password
  element_wattage: int
mqtt: true
services:
  - mqtt:need
